#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: sched
  username: rails
  password:
  socket: /tmp/mysql.sock
